services:
  - type: web
    name: bookbite-server
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: GOOGLE_BOOKS_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: REDIS_URL
        sync: false
      - key: CORS_ORIGIN
        value: https://your-ios-app-domain.com
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100